const breakfast = [
    { cat: "breakfast", title: "Skinnified Pork and Bean Burrito", price: 12.99, shortDisc: "How we dream about our future ", longDisc: "There once lived an old man and an old woman who were peasants and had to work hard to earn their daily bread. The old man used to go to fix fences and do other odd jobs for the farmers around, and while he was gone the old woman, his wife, did the work of the house and worked in their own little plot of land.", img: "https://i.ya-webdesign.com/images/food-plate-png-9.png" },

    { cat: "breakfast", title: "Salmon Sandwiches with Fries", price: 13.99, shortDisc: "How we dream about our future", longDisc: "Greg understood that this situation would make Michael terribly uncomfortable. Michael simply had no idea what was about to come and even though Greg could prevent it from happening, he opted to let it happen. It was quite ironic, really.", img: "https://i.ya-webdesign.com/images/food-top-view-png-15.png" },

    { cat: "breakfast", title: "Minty carrot, pistachio & feta salad", price: 8.99, shortDisc: "How we dream about our future", longDisc: "They rushed out the door, grabbing anything and everything they could think of they might need. There was no time to double-check to make sure they weren't leaving something important behind. Everything was thrown into the car and they sped off. Thirty minutes later they were safe and that was when it dawned on them that they had forgotten the most important thing of all", img: "https://i.ya-webdesign.com/images/food-top-view-png-14.png" },

    { cat: "breakfast", title: "Bang-Bang Shrimp", price: 13.99, shortDisc: "How we dream about our future", longDisc: "She sat in the darkened room waiting. It was now a standoff. He had the pong she had to endure the darkness, she wouldn't change her attitude. At three years old, Sandy's stubborn personality had already bloomed into full view", img: "https://i.ya-webdesign.com/images/food-plate-png-3.png" },

    { cat: "breakfast", title: "Instant Pot Turkey Chili", price: 7.99, shortDisc: "How we dream about our future", longDisc: "He watched as the young man tried to impress everyone in the room with his intelligence. There was no doubt that he was smart. The fact that he was more intelligent than anyone else in the room could have been easily deduced, but nobody was really paying any attention due to the fact that it was also obvious that the young man only cared about his intelligence", img: "https://i.ya-webdesign.com/images/food-dish-png-5.png" },

    { cat: "breakfast", title: "Oven Baked Chicken Tacos", price: 7.99, shortDisc: "How we dream about our future", longDisc: "She considered the birds to be her friends. She'd put out food for them each morning and then she'd watch as they came to the feeders to gorge themselves for the day. She wondered what they would do if something ever happened to her. Would they miss the meals she provided if she failed to put out the food one morning?", img: "https://i.ya-webdesign.com/images/food-plate-png-14.png" }
]
export default breakfast;