const dinner = [
    { cat: "dinner", key: "DINNER0", title: "Salmon Sandwiches with Fries", price: 6.99, shortDisc: "Position racks in the upper and lower thirds", longDisc: "Position racks in the upper and lower thirds of the oven; preheat to 425 degrees F. Toss the fries with 1 tablespoon olive oil on a baking sheet and sprinkle with the spiced salt. Bake on the lower oven rack, tossing halfway through, until golden, about 25 minutes.", img: "https://i.ya-webdesign.com/images/food-plate-png-6.png" },

    { cat: "dinner", key: "DINNER1", title: "Creamy chicken & mango curry", price: 7.99, shortDisc: "Season the salmon with kosher salt and", longDisc: "Season the salmon with kosher salt and pepper. Heat the remaining 1 tablespoon olive oil in a large ovenproof nonstick skillet over high heat. Reduce the heat to medium; add the salmon and cook until golden brown on the bottom, 5 minutes. Transfer the skillet to the upper oven rack; bake until the salmon is just opaque, about 3 minutes.", img: "https://i.ya-webdesign.com/images/food-plate-png-9.png" },

    { cat: "dinner", key: "DINNER2", title: "Slow-Cooker Cincinnati Chili", price: 9.99, shortDisc: "Spread some tartar sauce on the rolls", longDisc: "Spread some tartar sauce on the rolls. Sandwich with the salmon (cut into pieces, if needed), lettuce and tomatoes. Serve with the fries and more tartar sauce for dipping. Spread some tartar sauce on the rolls. Sandwich with the salmon (cut into pieces, if needed), lettuce and tomatoes. Serve with the fries and more tartar sauce for dipping", img: "https://i.ya-webdesign.com/images/food-plate-png-3.png" },

    { cat: "dinner", key: "DINNER3", title: "Beef and Vegetable Casserole", price: 11.99, shortDisc: "It was that terrifying feeling you", longDisc: "It was that terrifying feeling you have as you tightly hold the covers over you with the knowledge that there is something hiding under your bed. You want to look, but you don't at the same time. You're frozen with fear and unable to act. That's where she found herself and she didn't know what to do next", img: "https://i.ya-webdesign.com/images/food-plate-png-4.png" },

    { cat: "dinner", key: "DINNER4", title: "Creamy chicken & mango curry", price: 16.99, shortDisc: "If you can imagine a furry humanoid seven", longDisc: "If you can imagine a furry humanoid seven feet tall, with the face of an intelligent gorilla and the braincase of a man, you'll have a rough idea of what they looked like -- except for their teeth. The canines would have fitted better in the face of a tiger, and showed at the corners of their wide, thin-lipped mouths, giving them an expression of ferocity", img: "https://i.ya-webdesign.com/images/food-plate-png-14.png" },

    { cat: "dinner", key: "DINNER5", title: "Coconut & tamarind chicken curry", price: 10.99, shortDisc: "Cake or pie? I can tell a lot about", longDisc: "Cake or pie? I can tell a lot about you by which one you pick. It may seem silly, but cake people and pie people are really different. I know which one I hope you are, but that's not for me to decide. So, what is it? Cake or pie", img: "https://i.ya-webdesign.com/images/food-plate-png-6.png" }
]
export default dinner;